### ISSUE TITLE
Takeoff is not working after recent update

### ISSUE THREAD

**Issue by murugappanrm** [quasarcast/components-playground#5]
Hi Luke,

The Takeoff app is no longer working after the recent update(s). Even the landing page is no longer the same as the qpage does not show. I tried on the of the components "QButton" and it came out empty See image below. When i looked at the developer tools console, there many errors and warning.

![Takeoff - Qbutton](https://user-images.githubusercontent.com/63133893/176662038-1c5e1d56-75a4-4c9a-bff1-380f5c13b7b1.png)

I tested the old version and it seems to work fine. It looks like the new components added have problems.

**Comment by jdriesen** [comment]
Hi @murugappanrm ...

Sorry to say, but I strongly think there might be smt wrong at your side.
Over here, everything works perfectly fine.
(even the QButton page you're mentioning...)

![image](https://user-images.githubusercontent.com/1137648/176677984-fbf9aa23-aee7-4815-b536-57fb5e33a9ce.png)

**Comment by murugappanrm** [comment]
Hi, Are you on Windows platform?

**Comment by jdriesen** [comment]
Hi @murugappanrm ,

Yes, I am.

**Comment by murugappanrm** [comment]
Hi @jdriesen ,

Thank you for the update. Please help check the code. There are differences.  After some checking, this is what i found out.

**(1) Contrary to what i posted earlier, the code works except that new components added do not show a sample output.** 

![screencap1](https://user-images.githubusercontent.com/63133893/176790150-562d8063-df11-4b19-aa4f-24de59db1968.png)

**(2) On checking the playground code for QBadge, i found that it there was no code inserted.** 

![screencap2](https://user-images.githubusercontent.com/63133893/176790378-136aadba-0123-4f8b-96c2-6e219cc9f47b.png)

**(3) I decided to enter the code using video, I found the initial code in the video was using "defineComponent" (even app,vue) while the code in the playground was using "script setup" composition API.** 

![screencap3](https://user-images.githubusercontent.com/63133893/176790715-7097546e-fe04-40a4-9b69-752f33c89265.png)

**(4) Anyway, being a newbie, i entered the code in the playground and it worked.**

![screncap4](https://user-images.githubusercontent.com/63133893/176791408-666036cf-e149-4139-810f-97a4bbb2c8be.png)

**My feedback:**
Luke has done a wonderful job. The only feedback is that the older code that are present in the latest version of Takeoff have sample code but the new ones added do not. This is the cause of the misunderstanding. As a newbie, I was confused at first use.

**Comment by jdriesen** [comment]
Hi @murugappanrm ,

Happy you could solve your problem.
Enjoy learning Vue & Quasar.

(just follow the tuts from @ldiebold , in you'll become a pro in no time)

Cheers.
